### ISSUE TITLE
Option to save before formatting

### ISSUE THREAD

**Issue by Ptival** [berberman/vscode-cabal-fmt#1]
Most other formatting providers I use format what is currently in your buffer, or save before formatting.

This extension seems to format the file as it is currently on disk, which means that asking for the buffer to be formatted when you have not yet saved will give you a formatted version of the stale file on disk.

Simplest fix would be to perform a save before formatting.

Better fix but less easy would be to actually format the contents of the buffer, probably by creating a temporary file for it for `cabal-fmt` to work on.

**Comment by berberman** [comment]
Thanks for the advice! I think the current behaviour that formatting may overwrite unsaved changes is annoying too.
